from typing import Self, TypedDict

class ExamplePointer(TypedDict):
    start: int
    end: int
    example_size: int

class TFRecordFileReader:
    def __init__(self, tfrecord_filepath: str, save_index: bool = True) -> None: ...
    def __len__(self) -> int: ...
    def get_example(self, idx: int) -> bytes: ...
    def get_pointer(self, idx: int) -> ExamplePointer: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
