from typing import TypedDict

class ExamplePointer(TypedDict):
    start: int
    end: int
    example_size: int

class TFRecordFileReader:
    def __init__(self, tfrecord_filepath: str, save_index: bool = True) -> None: ...
    def __len__(self) -> int: ...
    def get_example(self, idx: int) -> bytes: ...
    def get_pointer(self, idx: int) -> ExamplePointer: ...
    def get_pointers(self) -> list[ExamplePointer]: ...
    def close(self) -> None: ...

def load_index_from_file_py(index_filepath: str) -> list[ExamplePointer]: ...
